const SongsArr = [
  {
    id: 1,
    name: "EveGaveAdamTheApple",
    artist: "Nicholas Ramirez",
    genre: "Trap, Hip-Hop",
    feeling: "Dark, thrilling",
    path: "../audio/EveGaveTheApple2Adam 80 bpm_4.mp3",
  },
  {
    id: 2,
    name: "Decompression",
    artist: "Nicholas Ramirez",
    genre: "Alternative, Hip-Hop",
    feeling: "Motivated, uplifted",
    path: "../audio/audioDecompression_2.wav",
  },
  {
    id: 3,
    name: "Do It Now",
    artist: "Nicholas Ramirez",
    genre: "Experimental, Hip-Hop",
    feeling: "strange, weird",
    path: "../audio/DO it now_5.mp3",
  },
  {
    id: 4,
    name: "SUPERFOODZ",
    artist: "Nicholas Ramirez",
    genre: "Experimental, Hip-Hop",
    feeling: "curious, strange",
    path: "../audio/audioSUPERFOODZ_4.mp3",
  },
  {
    id: 5,
    name: "Behind The Veil",
    artist: "Nicholas Ramirez",
    genre: "Experimental, Hip-Hop",
    feeling: "calm, strange",
    path: "../audio/_BehindTheVeil_1.mp3",
  },
  {
    id: 6,
    name: "ICANFEELITINMYSOUL",
    artist: "Nicholas Ramirez",
    genre: "Experimental, alternative",
    feeling: "thrilling",
    path: "../audio/I CAN FEEL IT IN MY SOUL.wav",
  },
  {
    id: 7,
    name: "REDHEAD",
    artist: "Nicholas Ramirez",
    genre: "Experimental, alternative",
    feeling: "calm",
    path: "../audio/REDHEAD sample 161 bpm_3.wav",
  },
  {
    id: 8,
    name: "Reverie",
    artist: "Nicholas Ramirez",
    genre: "Hip-Hop, trap",
    feeling: "thrilling",
    path: "../audio/Reverie.mp3",
  },
  {
    id: 9,
    name: "Airpod Pros No Interface",
    artist: "Nicholas Ramirez",
    genre: "Hip-Hop, trap",
    feeling: "thrilling",
    path: "../audio/Airpod Pros No Interface_8.mp3",
  },
  {
    id: 10,
    name: "Find 76",
    artist: "Nicholas Ramirez",
    genre: "Experimental, trap",
    feeling: "strange, weird",
    path: "../audio/Findr 76_5.wav",
  },
  {
    id: 11,
    name: "E FOR EA",
    artist: "Nicholas Ramirez",
    genre: "Experimental, Hip-Hop",
    feeling: "calm, thrilling",
    path: "../audio/E for EA.mp3",
  },
  {
    id: 12,
    name: "KALEAFZ",
    artist: "Nicholas Ramirez",
    genre: "Experimental, alternative",
    feeling: "calm, uplifted",
    path: "../audio/KAYLEAFZ_3.wav",
  },
  {
    id: 13,
    name: "Whats The Deel",
    artist: "Nicholas Ramirez",
    genre: "trap, Hip-Hop",
    feeling: "thrilling, strange",
    path: "../audio/KAYLEAFZ_3.wav",
  },
];

export default SongsArr;
